### ISSUE TITLE
in my account page when i edit my review it doesn't populate what i previously had in my review

### ISSUE THREAD

**Issue by meganm672** [muabria/Cookware.Critque#205]
**Describe the bug**
in my account page when i edit my review it doesn't populate what i previously had in my review

**To Reproduce**
1. Go to account page
3. Click on edit button for review
3. the review to edit is a blank screen

**Expected behavior**
would be nice to see what i had written on the review so that i can choose what to keep and what to change 

**Screenshots**
<img width="546" alt="Screenshot 2023-12-06 at 8 04 24 PM" src="ht
<img width="788" alt="Screenshot 2023-12-06 at 8 04 35 PM" src="https://github.com/muabria/Capstone/assets/137580670/dff1f87e-b074-44c9-af18-c8482e1dbec0">
tps://github.com/muabria/Capstone/assets/137580670/b7f311ae-6bc7-44c8-809c-80ccb3ac248d">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac
 - Browser [e.g. chrome, safari] chrome

**Additional context**
would be nice to have a little text show up as you hover over the buttons since the buttons are not words

**Comment by katc336** [comment]
- [ ] Edit Review
- [ ] Edit User
- [ ] Edit Comment
- [ ] Edit Equipment
