### ISSUE TITLE
Header hierarchy

### ISSUE THREAD

**Issue by paloobi** [muabria/Cookware.Critque#208]
**Describe the bug**
App Header is H3, and the "Explore Trusted Critiques Made from Real Users" header is also H3. 

**To Reproduce**
1. Click Find new kitchen equipment

**Expected behavior**
These shouldn't be the same hierarchy, and also the App Header ("Title Placeholder") should likely be an H1. If you need, you can adjust the size of each header with CSS, but the HTML should represent the hierarchy of the information accurately (eg. for screen readers)

**Screenshots**
![Screenshot 2023-12-06 at 5 08 52 PM](https://github.com/muabria/Capstone/assets/8248496/708a17d6-94a3-46cd-957e-d1038da79a64)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome

**Comment by mvandell** [comment]
Home page header/NavBar header too
